### ISSUE TITLE
MongoDB with Mongoose example

### ISSUE THREAD

**Issue by freiksenet** [apollographql/launchpad#37]

**Comment by b-barry** [comment]
Could I tackle it?
I propose to "translate" the MongoDB example https://launchpad.graphql.com/vkmr1kl83 
using mongoose

**Comment by stubailo** [comment]
That sounds great!

**Comment by b-barry** [comment]
@stubailo Cool !
I did it here : https://launchpad.graphql.com/m55w845j9
What do you think ?

**Comment by stubailo** [comment]
@b-barry please click "save" in the query section to save an example query!

**Comment by b-barry** [comment]
@stubailo Sorry for the delay, I saved an example query. Do I create a PR?

**Comment by ilabacheuski** [comment]
https://launchpad.graphql.com/qmp7m8nq3p
With an article in medium
https://medium.com/handlebar-labs/graphql-authentication-with-react-native-apollo-part-1-2-9613aacd80b3

**Comment by alexneo2003** [comment]
@b-barry hi, man.
i'm forking your example (https://launchpad.graphql.com/m55w845j9) and it's not working.
i'm receive next error
`SyntaxError: Unexpected token I in JSON at position 0
    at https://launchpad.graphql.com/static/js/main.8ecc894c.js:1:741833`

will you try reproduce?
my [launchpad](https://launchpad.graphql.com/xnrj3r148l)

**Comment by ziadrida** [comment]
I get the same error: SyntaxError: Unexpected token I in JSON at position 0
    at https://launchpad.graphql.com/static/js/main.8ecc894c.js:1:741833

**Comment by AkezhanOb1** [comment]
@ziadrida have u solved it?
