### ISSUE TITLE
Forked an example launchpad and got missing graphql-extension module error

### ISSUE THREAD

**Issue by cenjennifer** [apollographql/launchpad#90]
I forked an example launchpad (GraphQL.js code sample with mutation: https://launchpad.graphql.com/98lpqv3rr ) and before i make any changes, I get this `graphql-extension` module error. Anyone know why and the solution to fix this?

```
{
  "code": 400,
  "message": "Compilation failed: Cannot find module 'graphql-extensions'",
  "error": "Cannot find module 'graphql-extensions'",
  "stack": "Error: Cannot find module 'graphql-extensions'\n    at Function.Module._resolveFilename (module.js:325:15)\n    at Function.WebtaskModule._resolveFilename (/data/sandbox/lib/module.js:25:27)\n    at WebtaskModule.require (/data/sandbox/lib/module.js:101:39)\n    at require (/data/sandbox/lib/module.js:136:21)\n    at /data/io/6d62e231-2b82-4fad-a61e-a8bfc60f04ac/webtask.js:77:29\n    at Object.<anonymous> (/data/io/6d62e231-2b82-4fad-a61e-a8bfc60f04ac/webtask.js:221:5)\n    at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:95:34)\n    at defaultJavascriptCompiler (/data/sandbox/lib/compiler.js:119:30)\n    at defaultCompiler (/data/sandbox/lib/compiler.js:128:16)\n    at /data/sandbox/lib/compiler.js:231:17"
}
```

**Comment by jlowen** [comment]
I had the same problem. Went to type in the editor pane and it magically started working.

**Comment by asicfr** [comment]
@evans I have a same issue

**Comment by gandhiamarnadh** [comment]
@evans facing same issue

**Comment by joaovicente** [comment]
@evans experienced the same issue today
